#!/bin/bash


pokemon=('bulbasaur' 'ivysaur' 'venusaur' 'charmander' 'charmeleon')

for name in "${pokemon[@]}"
do
    echo $(jq -arg name "$name" '.[] | select(.name | ascii_downcase == ($name | ascii_downcase))') > "${name}.json"
done