#!/bin/bash


pokemon=('bulbasaur' 'ivysaur' 'venusaur' 'charmander' 'charmeleon')

for name in "${pokemon[@]}"
do
    echo "Fetching data for ${name}..."
    entry=$(curl -s "https://pokeapi.co/api/v2/pokemon/$name")
    sleep 5
    echo "$entry" > "${name}.json"
    echo "Saved data to ${name}.json"

done